### ISSUE TITLE
Opening UML Modeller takes a long time

### ISSUE THREAD

**Issue by unifab** [opengds/OpenGDS#29]
I installed the latest version for LabVIEW 2016 (32bits)  from http://opengds.github.io/ 
I installed using Installer_OpenGDS_1.2.12(Master)_LV2016-32.vi

The UML Modeller takes more than 5 minutes to open, one time took almost 20 minutes.

**Comment by kosist** [comment]
**unifab**, did you try to recompile the UML project in LV installation folder? If so, did it help? For me it helped a little bit...

**Comment by MikaelHolmstrom** [comment]
I'm guessing it wasn't pre-compiled fully.
It was probably compiled with the LV2016 version with no patch (f?), so maybe your LV version needed to recompile it. And since all VIs are read only and contain the source code it will need to re-compile it every time. I'll work on this for the next release.
