### ISSUE TITLE
Clone class fails if parent class is Read only

### ISSUE THREAD

**Issue by MikaelHolmstrom** [opengds/OpenGDS#76]

**Comment by Bas-vE** [comment]
I was thinking about tackling this issues in the upcoming month because with SVN locking this is really annoying,.

The main reason this is happening is because there is probably a save mechanism that cannot be done because the class is read only, same goes if the project is read only. Wouldn't it be better to not save anything and let the user do this when he pleases? I also think this will prevent some issues when doing this stuff when the project is not saved after creating

**Comment by Bas-vE** [comment]
I've been testing this since the last version and this seems resolved.
